### PR TITLE
feat: update translation files

### PR DESCRIPTION
**Pull request by myml**
优化界面文案, 更新翻译文件

Log: 补充翻译

### CODE REVIEW

**Comment by Zeno-sole** [comment]
> **AutoIntegrationPr Bot** auto integrate with pr url: [deepin-community/Repository-Integration#150](https://github.com/deepin-community/Repository-Integration/pull/150) PrNumber: 150 PrBranch: auto-integration-5011374228

补充一下信息

**Comment by Zeno-sole** [comment]
> **AutoIntegrationPr Bot** auto integrate with pr url: [deepin-community/Repository-Integration#150](https://github.com/deepin-community/Repository-Integration/pull/150) PrNumber: 150 PrBranch: auto-integration-5011374228

重新触发了 可以继续展开集成测试

**Comment by Zeno-sole** [comment]
测试通过了，可以合并了

**Review by justforlxz — APPROVED** [review]

**Pull request merged**
