### PR TITLE
Release/1.2.2

### PR DESCRIPTION
**Pull request by myml**
- https://github.com/linuxdeepin/developer-center/issues/4903
- https://github.com/linuxdeepin/developer-center/issues/4901
- https://github.com/linuxdeepin/developer-center/issues/4898

### CODE REVIEW

**Comment by myml** [comment]
创建集成Issues的流程卡了，可以使用下面的仓库测试
https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-240/testing/

**Comment by myml** [comment]
@justforlxz 麻烦加下分，好创建tag

**Review by justforlxz — APPROVED** [review]

**Comment by justforlxz** [comment]
> @justforlxz 麻烦加下分，好创建tag

已处理

**Pull request merged**
